[2025-04-01T06:17:00.766+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T06:17:00.787+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dbt_spark_oracle.dbt_run manual__2025-04-01T06:16:57.897980+00:00 [queued]>
[2025-04-01T06:17:00.797+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dbt_spark_oracle.dbt_run manual__2025-04-01T06:16:57.897980+00:00 [queued]>
[2025-04-01T06:17:00.798+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-01T06:17:01.003+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_run> on 2025-04-01 06:16:57.897980+00:00
[2025-04-01T06:17:01.013+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=125) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-01T06:17:01.016+0000] {standard_task_runner.py:72} INFO - Started process 127 to run task
[2025-04-01T06:17:01.017+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dbt_spark_oracle', 'dbt_run', 'manual__2025-04-01T06:16:57.897980+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dbt-spark-oracle.py', '--cfg-path', '/tmp/tmpzu_ikhhb']
[2025-04-01T06:17:01.022+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask dbt_run
[2025-04-01T06:17:01.084+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dbt_spark_oracle.dbt_run manual__2025-04-01T06:16:57.897980+00:00 [running]> on host 9e396ea3ea82
[2025-04-01T06:17:01.207+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dbt_spark_oracle' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T06:16:57.897980+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T06:16:57.897980+00:00'
[2025-04-01T06:17:01.209+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-01T06:17:01.210+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-01T06:17:01.211+0000] {logging_mixin.py:190} INFO - Current task name:dbt_run state:running start_date:2025-04-01 06:17:00.788281+00:00
[2025-04-01T06:17:01.211+0000] {logging_mixin.py:190} INFO - Dag name:etl_dbt_spark_oracle and current dag run status:running
[2025-04-01T06:17:01.214+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-01T06:17:01.218+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-01T06:17:01.220+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/dbt_spark_project && /opt/spark/sbin/start-thriftserver.sh --master local[*] --hiveconf hive.metastore.warehouse.dir=/opt/spark/spark-warehouse --hiveconf javax.jdo.option.ConnectionURL="jdbc:derby:;databaseName=/opt/spark/metastore_db;create=true" && sleep 10 && dbt run']
[2025-04-01T06:17:01.237+0000] {subprocess.py:99} INFO - Output:
[2025-04-01T06:17:01.248+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: cd: /dbt/dbt_spark_project: No such file or directory
[2025-04-01T06:17:01.250+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-01T06:17:01.267+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-01T06:17:01.275+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-01T06:17:01.276+0000] {logging_mixin.py:190} INFO - Task start:2025-04-01 06:17:00.788281+00:00 end:2025-04-01 06:17:01.275100+00:00 duration:0.486819
[2025-04-01T06:17:01.277+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_run> dag:<DAG: etl_dbt_spark_oracle> dagrun:<DagRun etl_dbt_spark_oracle @ 2025-04-01 06:16:57.897980+00:00: manual__2025-04-01T06:16:57.897980+00:00, state:running, queued_at: 2025-04-01 06:16:57.938694+00:00. externally triggered: True>
[2025-04-01T06:17:01.278+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-04-01T06:17:01.280+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=etl_dbt_spark_oracle, task_id=dbt_run, run_id=manual__2025-04-01T06:16:57.897980+00:00, execution_date=20250401T061657, start_date=20250401T061700, end_date=20250401T061701
[2025-04-01T06:17:01.336+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-01T06:17:01.337+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 127)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-01T06:17:01.363+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-01T06:17:01.375+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
